from . import resource
from . import booking
from . import additional_info
from . import booking_request
from . import helpers
from . import booking_type
from . import calendar_attendee
from . import calendar_event
from . import booking_service
from . import res_partner